FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ./services/deckbrew.api/ ./services/deckbrew.api/
RUN dotnet restore ./services/deckbrew.api/DeckBrew.Api.csproj
RUN dotnet publish ./services/deckbrew.api/DeckBrew.Api.csproj -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=http://0.0.0.0:8080
ENTRYPOINT ["dotnet", "DeckBrew.Api.dll"]
